- hosts: 172.31.1.25
  become: true
  tasks:
  
  - name: Remove previous code
    file:
      path: /var/www/html/website
      state: absent

  - git:
      repo: https://github.com/teenabodhwani/Project1-A1.git
      dest: /var/www/html/website
